### ISSUE TITLE
java.lang.RuntimeException: unable to unregister handler for event: SETLIST_COMPLETE

### ISSUE THREAD

**Issue by mimelator** [mimelator/apv#1]
java.lang.RuntimeException: unable to unregister handler for event: SETLIST_COMPLETE
		at com.arranger.apv.helpers.APVCallbackHelper.lambda$resetHandlerMap$0(APVCallbackHelper.java:37)
		at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
		at com.arranger.apv.helpers.APVCallbackHelper.resetHandlerMap(APVCallbackHelper.java:33)
		at com.arranger.apv.agent.APVAgent.reloadConfiguration(APVAgent.java:23)
		at com.arranger.apv.Main.reloadConfiguration(Main.java:938)
		at com.arranger.apv.model.SetPackModel.launchSetPack(SetPackModel.java:101)
		at com.arranger.apv.gui.SetPackLauncher$1.mouseClicked(SetPackLauncher.java:46)

	Repro: ./apv-no-db.sh default
		Open Window
		Load 5 set packs
		Cycle Set Pack (twice in quick succession?)

**Comment by mimelator** [comment]
Set Packs are a deprecated feature
