### ISSUE TITLE
line in exception

### ISSUE THREAD

**Issue by mimelator** [mimelator/apv#24]
https://steamcommunity.com/app/1091220/discussions/0/1640916564840389625/

Here it is....but too bad the real error showing up at the end of the shell window doesn´t get captured in the logfile. I doubt this is useful. 

and this here is the rest that is missing in the log file:

Listening to line in
=== JavaSound Minim Error ====
D X
--- Unable to return a TargetDataLine: unsupported fo rmat - PCM SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, littlendian
Minim Error ===
Minim.getLinein: attempt fa iled, could not secure an Audioinput.
·ava.lang.NullPointerException
at com.arranger.a pv.audio.Beatinfo.setup(Beatinfo.java:43)
at com.arranger.a pv.audio.Beatinfo.<init>(Beatinfo.java:22)
at com.arranger.a pv.audio.Audio.<init>(Audio.java:46)
at com.arranger.a pv.Main.setup(Main.java:948)
at processing.core. PApplet. handleDraw( PApplet.java:2401)
at processing.o pengl. PSurfaceJOGL$DrawListener.display( PSurfaceJOGL.java:866)
at jogamp.opengl.GLDrawableHelper.dis playimpl(GLDrawableHelper.java:692)
at jogamp.opengl.GLDrawableHelper.dis play(GLDrawableHelper.java:674)
at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
at jogamp.opengl.GLDrawableHelper.invo keG Lim pl(GLDrawableHelper.java:1293)
at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
at com.jogamp.ne11t.opengl.GLWindow.display(GLWindow.java:759)
at com.jogamp.opengl.util.AWTAnimatorimpl.display(AWTAnimatorimpl.java:81)
at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
at com.jogamp.opengl.util.F PSAnimator$MainTask.run(F PSAnimator.java:178)
at java.util.TimerThread.mainLoop(Unknown Source)
at java.util.TimerThread.run(Unknown Source)

**Comment by mimelator** [comment]
You're absolutely correct.  The log file isn't capturing enough of the useful info, but the stack trace you captured from the shell was excellent.  Thank you.

I think one possibility is that Wavelength is requesting access to the microphone.  It's possible that System permissions restrict access to Wavelength.  I will investigate a way to automatically detect this, but in the meantime you could see if the microphone on your computer has any permissions.

Thanks again,
Mark

**Comment by mimelator** [comment]
One option is to ship a tiny test app that checks to see if various input audio lines are available

**Comment by mimelator** [comment]
Configuring Wavelength to auto select a usable audio input line
